% Each new term in the Fibonacci sequence is generated by adding the previous
% two terms. By starting with 1 and 2, the first 10 terms will be:
% 
% 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
% 
% By considering the terms in the Fibonacci sequence whose values do not exceed
% four million, find the sum of the even-valued terms.

FibSerie = [1 2];

for i = 3:9999999
    Value = FibSerie(i-2) + FibSerie(i-1);
    if Value > 4000000
        break
    else
        FibSerie(i) = Value;
    end
end

FibSerie(1:5)
Sum = 0
for i = 1:length(FibSerie)
    if mod(FibSerie(i),2) == 0
        Sum = Sum + FibSerie(i);
    end
end

Sum